### ISSUE TITLE
incomplete federated istio deployment 

### ISSUE THREAD

**Issue by karmab** [danehans/fedv2-manifests#1]
getting this when deploying

```
Failed to create version PropagatedVersion "clusterrole-istio-cleanup-secrets-istio-system": an empty namespace may not be set during creation
```
does it ring a bell ?

**Comment by danehans** [comment]
@karmab federated istio has moved to it's own repo: https://github.com/danehans/federated-istio Please follow the docs there and open an issue if you run into any problems. I will make mention of the move or remove the istio content from this repo. I apologize, I should have made note of it.

**Comment by karmab** [comment]
thanks @danehans !
